sudo: required
services:
  - docker

#dev
deploy:
- provider: elasticbeanstalk
  region: us-east-1
  app: MaxImport-dev
  env: MaxImport-backend
  bucket_name: elasticbeanstalk-us-east-1-691046028389
  bucket_path: MaxImport-dev
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY